### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by khiem20tc** [dranikpg/dto-mapper#2]
What are any solutions to improve performance when using DTO pattern automation? It's looking good to me but I still considering performance ^^

**Comment by dranikpg** [comment]
Hi

The problem is that automatic dto mapping uses reflection to get information about types at runtime. This means that in comparison to hand-written mapping code, it can't be efficiently compiled down. And there is unfortunately no way around it 🙂 

You can either write your mapping code in performance critical cases or check out code generator tools. I remember there were some libraries that were able to generate mapping code (however properly setting up codegen can be a little inconvenient).
